### ISSUE TITLE
img_lab normalization

### ISSUE THREAD

**Issue by Sweetii-huan** [karoly-hars/GAN_image_colorizing#3]
Could you please explain the meaning of this code when doing normalization for img_lab?

img_bgr = img_bgr.astype(np.float32)/255.0
# transform to lab
img_lab = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2LAB)
# normalize
    img_lab[:, :, 0] = img_lab[:, :, 0]/50 - 1
    img_lab[:, :, 1] = img_lab[:, :, 1]/127
    img_lab[:, :, 2] = img_lab[:, :, 2]/127

**Comment by karoly-hars** [comment]
Hello,

The following line converts the BGR image from 8 bit to 32 bit, and scales the pixel values to [0, 1] from [0, 255]
```img_bgr = img_bgr.astype(np.float32)/255.0```.

The line ```img_lab = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2LAB)``` calls the BGR->CIE L*a*b* converter of OpenCV.
The documentation for this can be found at https://docs.opencv.org/3.4/de/d25/imgproc_color_conversions.html.

After the conversion is done, according to the documentation of OpenCV, L (the first channel of the images) is between 0 and 100, and the other two channels, a and b are between -127 and 127.

I apply the following code
```
img_lab[:, :, 0] = img_lab[:, :, 0]/50 - 1
img_lab[:, :, 1] = img_lab[:, :, 1]/127
img_lab[:, :, 2] = img_lab[:, :, 2]/127
```
to scale everything to the [-1, 1] interval. This is necessary for two reasons:
1. it is usually a good idea to normalize the inputs before they go into a network
2. the generator network in https://github.com/karoly-hars/GAN_image_colorizing/blob/master/networks.py has a tahn activation function in its last layer, thus its output is also scaled between -1 and 1

**Comment by Sweetii-huan** [comment]
Thank you for your reply, but I still don't understand the normalization of L channel. Isn't the value range of L channel 0 to 100?
And why you have to subtract 1 at the end.

**Comment by karoly-hars** [comment]
After the BGR to LAB transformation, it is between 0 and 100. After dividing by 50 it is between 0 and 2. After I subtract 1 it is between -1 and 1.

**Comment by Sweetii-huan** [comment]
Thank you very much for your reply.
